import {
  ShoppingCart,
  Utensils,
  Car,
  Home,
  Heart,
  BookOpen,
  Coffee,
  Plane,
  Shirt,
  Zap,
  Gift,
  Wallet,
  Dumbbell,
  Music,
  Baby,
  Scissors,
  PawPrint,
  Smartphone,
  Bot,
  BottleWine,
  Briefcase,
  BusFront,
  Cake,
  Candy,
  ChartCandlestick,
  Joystick,
  Landmark,
  Banknote,
  Laptop,
  TrendingUp,
  Coins,
  Building2,
  PartyPopper,
  type LucideIcon,
} from 'lucide-react-native';

export const ICON_MAP: Record<string, LucideIcon> = {
  shopping: ShoppingCart,
  food: Utensils,
  transport: Car,
  home: Home,
  health: Heart,
  education: BookOpen,
  cafe: Coffee,
  travel: Plane,
  fashion: Shirt,
  telecom: Zap,
  gift: Gift,
  wallet: Wallet,
  fitness: Dumbbell,
  music: Music,
  baby: Baby,
  beauty: Scissors,
  pet: PawPrint,
  digital: Smartphone,
  bot: Bot,
  wine: BottleWine,
  work: Briefcase,
  bus: BusFront,
  cake: Cake,
  candy: Candy,
  invest: ChartCandlestick,
  game: Joystick,
  bank: Landmark,
  salary: Banknote,
  freelance: Laptop,
  dividend: TrendingUp,
  allowance: Coins,
  rental: Building2,
  party: PartyPopper,
};
