import {
  ShoppingCart,
  Utensils,
  Car,
  Home,
  BookOpen,
  Coffee,
  Plane,
  Shirt,
  Zap,
  Gift,
  Wallet,
  Music,
  Baby,
  Scissors,
  PawPrint,
  Smartphone,
  Bot,
  Briefcase,
  BusFront,
  Cake,
  Candy,
  ChartCandlestick,
  Joystick,
  Landmark,
  Banknote,
  Laptop,
  Building2,
  PartyPopper,
  BicepsFlexed,
  GraduationCap,
  HandHeart,
  Shapes,
  Pill,
  type LucideIcon,
  Beer,
  Cigarette,
} from 'lucide-react-native';

export const ICON_MAP: Record<string, LucideIcon> = {
  shopping: ShoppingCart,
  food: Utensils,
  cafe: Coffee,
  bus: BusFront,
  home: Home,
  digital: Smartphone,
  drug: Pill,
  telecom: Zap,
  fashion: Shirt,
  candy: Candy,
  party: PartyPopper,
  transport: Car,
  bank: Landmark,
  fitness: BicepsFlexed,
  baby: Baby,
  wine: Beer,
  education: BookOpen,
  beauty: Scissors,
  music: Music,
  invest: ChartCandlestick,
  wallet: Wallet,
  travel: Plane,
  pet: PawPrint,
  bot: Bot,
  work: Briefcase,
  cake: Cake,
  game: Joystick,
  salary: Banknote,
  freelance: Laptop,
  rental: Building2,
  study: GraduationCap,
  donate: HandHeart,
  gift: Gift,
  cigarette: Cigarette,
  things: Shapes,
};
